### ISSUE TITLE
Allow icon placement outside of address bar

### ISSUE THREAD

**Issue by Markus00000** [tosdr/tosdr.org#151]
Users who don't want add-on icons in the address bar would welcome being able to place the icon elsewhere. Many add-ons allow their icon to be placed in any bar (e.g. the tab bar or bookmarks toolbar).

As Firefox is highly customizable, users can even have the address bar hidden.

**Comment by hugoroy** [comment]
See https://github.com/tosdr/tosdr-firefox/issues/31
