### ISSUE TITLE
tosdr does not seem to work

### ISSUE THREAD

**Issue by wolfgangus** [tosdr/tosdr.org#153]
Hey guys,
I did a fresh install of firefox and installed tosdr, but it seems to not work. 

Some more information:
1. This was a fresh install of both windows and firefox
2. The only add-on initially installed was uBlock, which I disabled and yet tosdr failed to work 

![1](https://cloud.githubusercontent.com/assets/6940910/8043133/773e6b12-0e41-11e5-92f7-5ff275e3a0f8.PNG)

![2](https://cloud.githubusercontent.com/assets/6940910/8043146/8f05f06c-0e41-11e5-82e9-4e4fc05e83b0.PNG)

I don't know what other info I must provide - so please ask me if you need more.

**Comment by hugoroy** [comment]
What do you see in the URL bar on this page @wolfgangus ? You shuold see the tosdr icon (as Github has a "B" rating)

**Comment by pierreozoux** [comment]
@wolfgangus I didn't manage to reproduce, could you give more information please?

**Comment by pierreozoux** [comment]
The extension doesn't work in private mode.
