### ISSUE TITLE
Clarify where to submit new TOS

### ISSUE THREAD

**Issue by jmatsushita** [tosdr/tosdr.org#162]
Hi there,

I've come across a lot of different instructions on how to submit a new term of service to TOSDR:
- On the TOSDR Get Involved page: https://tosdr.org/get-involved.html 
  - At the top, an "Alpha - Submit the URL of the terms to ToSBack.org" button linking to an embedded Google Form https://tosdr.org/submit-tosback.html
  - In Paragraph Step 1: find the Terms of a website, points to:
    - the tosdr/tosback2 wiki which explains how to submit a pull request: https://github.com/tosdr/tosback2/wiki/How-To-Contribute-Terms-Location#putting-it-all-together 
    - Emailing eff at tosback2@eff.org
- On the TOSBack website itself:
  - There's a link to a web front end: https://tosback.eff.org/web_front_end/

Are all of these still valid? Will submitting a pull request on https://github.com/tosdr/tosback2 be picked up?

Cheers,

Jun

**Comment by hugoroy** [comment]
The other one is maintained by Internet Society and EFF so I don't know.

The one indicated on tosdr.org is not very reliable. @JimmStout?
-- 
Envoyé de mon appareil mobile. 
Sent from my mobile device.

**Comment by hugoroy** [comment]
Have you checked if you can do this in edit.tosdr.org?

**Comment by michielbdejong** [comment]
Hi @jmatsushita,

First of all, are you talking about contributing to tosdr.org or about tosback.org? The two projects are currently not really connected. For tosback.org, if you want to edit or add a crawling-rule, you should open an issue or pull request on https://github.com/tosdr/tosback2.

For tosdr.org, if you want to submit review points, the way to do it is still to send a post to the tosdr mailing list, saying which service it's about, whether it's a good (positive) or bad (negative) point, quoting the passage and the URL on which you read it, and explaining your opinion about it. You can browse https://groups.google.com/forum/#!forum/tosdr for some examples.

Maybe the thing that's most confusing in the instructions you quoted is the difference between tosdr.org and tosback.org?
