### ISSUE TITLE
The world move a bit...

### ISSUE THREAD

**Issue by hellekin** [tosdr/tosdr.org#168]
I was checking tosdr.org today and found a number of annoying things:

- the flattr site is dead, but linked many times on the site.
- the indieagogo campaign is 404 as well
- the recommendations are still v1 but v2's edit.tosdr.org is under way
- many topics in edit.tosdr.org are uncategorized.

As I'm still looking forward to implement EU-based terms of service of class A, I'm wondering about the status of the project and how to deal with these issues.

**Comment by michielbdejong** [comment]
We're actually in the process of rebooting it a bit -  would be great if you can join our community call!

Announcement: https://groups.google.com/forum/#!topic/tosdr/U8J3dHSVtqY

Date picker: https://framadate.org/sAleAIfcyyzS425z

**Comment by hellekin** [comment]
Ack.  I'm waiting for confirmation: usually Thursday and Friday evenings are quite busy, but I definitely want to hear from you :)

**Comment by hellekin** [comment]
Hey there, are we not supposed to have a talk now?

**Comment by hugoroy** [comment]
On 2017-09-22 18:07, hellekin wrote:
> Hey there, are we not supposed to have a talk now?
> 

Yes, at 19:00 Paris time but i'm stuck in a meeting with a client :(

**Comment by michielbdejong** [comment]
In the end some people started at 18:00 Paris time, we ended at 19:30 Paris time. Next time we'll meet in a less confusing timezone. :)

https://groups.google.com/d/msg/tosdr/U8J3dHSVtqY/svP0JkcMAgAJ
