### ISSUE TITLE
Taking down problematic point

### ISSUE THREAD

**Issue by hugoroy** [tosdr/tosdr.org#176]
I see this: https://github.com/tosdr/tosdr.org/blob/2c900c7cf4d4c3a2ce0ae1d9523cca73383dc6b0/points/i3Fx2yL3q1g.json

This seems wrong to me.

Technical permissions are in no way something that ToS;DR should cover. Technical permissions may sometimes be required by an app to work. This is a completely different assessment. Technical permissions may also be subject, and limited by, the ToS.

The point we make here is serious, and I don't see enough data to back it up. It should be taken down.

(I am getting tweets from people citing this example).

@michielbdejong : the whole "case" seems like this.

**Comment by michielbdejong** [comment]
ok, I'll mark it as disputed

**Comment by hugoroy** [comment]
Thanks a lot :)
