### ISSUE TITLE
deal with rating system differences between tosdr.org and phoenix

### ISSUE THREAD

**Issue by michielbdejong** [tosdr/tosdr.org#183]
The site has the following rating system:
* points are rated good / neutral / bad / blocker and on top of that, a weight from 0 to 100
* services are rated based on their points, as per https://github.com/tosdr/tosdr-build/blob/master/scripts/checkclasses.js#L29-L39:
  * add the weights of all good points
  * substract the weights of all bad points
  * substract the weights of all blocker points
  * substract an extra 100 for each blocker point
  * if the result is <-500, e.g. 10 bad points with weight 50 each, or 3 blocker points with weight 67 each, the service gets class E
  * if the service did not get class E, but there is at least one blocker, the service still gets class D
  * if the result is between -500 and -200, but there are no blockers, the service gets class C
  * if the result is above -200, but there is at least one bad point, the point gets class B  
  * if there are no bad points and no blockers, the service gets class A

Phoenix has a slightly, but significantly, different rating system, see https://github.com/tosdr/phoenix/wiki#rating:
* I think points now also get good / neutral / bad / blocker, even though this is not documented on the wiki
* As implemented in https://github.com/tosdr/phoenix/blob/master/app/models/service.rb#L40-L49 services get rated by assigning 0 to blockers, 2 to bad points, 5 to neutral points and 8 to good points, and then taking the average of that; `0-2 -> F`, `3-4 -> D`, `5-6 -> C`, `7-8 -> B`, `9-10 -> A`

This means a services with only good points gets a B in Phoenix (getting an A is impossible? see https://github.com/tosdr/phoenix/issues/375)

**Comment by Vinnl** [comment]
Fixed by #378.
