### ISSUE TITLE
Consider using Firebase.io as distributed database backend?

### ISSUE THREAD

**Issue by dragon788** [tosdr/tosdr.org#211]
It has some really powerful data points and graphing as well as extremely fast storage and integration with many Javascript frameworks.

**Comment by mozdevcontrib** [comment]
Firebase.io as in Google’s Firebase via React? As an organization concerned with Privacy Practices, wouldn’t it be best to avoid Google?

**Comment by JustinBack** [comment]
Closing issue, stale
