### ISSUE TITLE
New Feature: submit ToS and PP urls to ToSBack

### ISSUE THREAD

**Issue by hugoroy** [tosdr/tosdr.org#213]
For now I made: https://tosdr.org/submit-tosback.html

**Comment by cauerego** [comment]
i never used gatsbyjs or 5apps, but unless you can put them both together i really do think it's worth considering another host. (gatsbyjs will probably be my next main website tool, for many reasons... here i just learned a new one, that) building a form should be trivial:

https://www.gatsbyjs.com/docs/building-a-contact-form/

**Comment by weisk** [comment]
Hi guys, may I be of any service to you?
