### ISSUE TITLE
Many missing logos on the Ratings section on the homepage

### ISSUE THREAD

**Issue by JesseWeinstein** [tosdr/tosdr.org#219]
E.g. IMDB, Trello. Is there a way to add these thru the edit interface yet?

**Comment by RambosRide** [comment]
My service image is broken too...plus I cannot seem to get the service rated - it's only partially done. I would really love to work with someone to do both 1) get my service across the finish line and published on tosdr 2) work more on contributing possibly - I've got 25 years of programming experience but not sure what I could do.

**Comment by JustinBack** [comment]
We have created a new submission process for new icons:

https://forum.tosdr.org/icon
