### ISSUE TITLE
Missing quote-text filed 

### ISSUE THREAD

**Issue by senjed** [tosdr/tosdr.org#224]
I have a question regarding the  json files in https://github.com/tosdr/tosdr.org/tree/master/api/1/service. Some of the points do not contain the "qoute-text" key. Why is that? and how can I get the qoute-text for these cases?

**Comment by Vinnl** [comment]
Unfortunately the ability to link points to a quote is a somewhat recent addition, so my hunch is that the points you looked at were created before that ability.

Additionally, it's still possible to create a point without linking it to a quote - not all the points are based on text in the terms of service, e.g. the ability to update your personal details can also just be exposed in the interface.

**Comment by senjed** [comment]
@Vinnl so, in this case, how can I get the text snippet that was rated? Is it fine to look at the "case" field? (I know this is not the exact quote of the TOS though)

**Comment by Vinnl** [comment]
@senjed Well, it means there _is no_ text snippet that was rated; or at least none that was stored by us. You could look at the case; it should be relevant to the point - just be sure to be aware that that text was not actually found in the respective service.
