### ISSUE TITLE
Missing services on home page

### ISSUE THREAD

**Issue by ghost** [tosdr/tosdr.org#225]
several services and websites are missing from both the annotate tool and the home page ratings search. However, when I try to add a service it says the name already exists.
It seems like the search engines aren't pulling the results
an example would be pixabay. Searching for this service's rating at the home page brings up a blank page, but it exists in annotate mode.
Then dailymotion doesn't show in either search options, but I can't add it as the name already exists

**Comment by RambosRide** [comment]
My service is in the same LIMBO - the service has an A rating in the annotate tool...but doesn't show anywhere else. I've been trying for months to resolve...can anyone help.
Service 420A3.com

**Comment by Vinnl** [comment]
@RambosRide That appears to be a different case from this issue: your service only has four approved points, and a service's rating is only published after points have been approved covering all [these topics](https://github.com/tosdr/tosdr.org/wiki/checklist), and a Curator has marked it as such. Unfortunately, our Curators are volunteers with limited availability, so the queue of points that have yet to be approved isn't processed as swiftly as would be ideal - though our volunteers are working very hard!

(As for @kitcallie's issue: I can't tell what the reason for that is, unfortunately. And like our Curators, the developers that might be able to fix this are volunteers as well, and in even shorter supply...)

**Comment by michielbdejong** [comment]
I'm running the deploy script now to transfer data from edit.tosdr.org to tosdr.org, i think we're now at the point where we should probably put that on a cron job.

**Comment by kitcallie** [comment]
@Vinnl I wish I knew coding and programming to better help. At this time however I can only contribute 😭
@michaeibdejong from what I understand a cron job to be, it sounds like a great idea. 👍 I hope tos;dr catches up soon. I adore the concept and wish I could better help.

**Comment by RambosRide** [comment]
> 
> 
> @RambosRide That appears to be a different case from this issue: your service only has four approved points, and a service's rating is only published after points have been approved covering all [these topics](https://github.com/tosdr/tosdr.org/wiki/checklist), and a Curator has marked it as such. Unfortunately, our Curators are volunteers with limited availability, so the queue of points that have yet to be approved isn't processed as swiftly as would be ideal - though our volunteers are working very hard!
> 
> (As for @kitcallie's issue: I can't tell what the reason for that is, unfortunately. And like our Curators, the developers that might be able to fix this are volunteers as well, and in even shorter supply...)

Vinnl - thank you for the additional information, I wasn't aware I needed to cover all the points on the link/page you posted, I'll make that happen in the next couple days. Thanks again! Dan

**Comment by RambosRide** [comment]
Hello!
So we made some progress - outstanding!

The 420A3.com service is showing on the main page with a broken logo image and no class assigned yet. 

![TSDR1](https://user-images.githubusercontent.com/8228156/69002352-5e6ac080-08a2-11ea-9152-303da64a1c7f.png)

Now..to drive it home :)

What can I do to help speed this along so I can reference ToS;DR ratings and so people can see it on the DDG/ToS;DR browser extension?

Thanks
Dan

**Comment by RambosRide** [comment]
BUMP - I'll do whatever it takes - anyone????

**Comment by RambosRide** [comment]
BUMP - I'm sad :( - No one responds on any level of contact twitter, github nothing.

I think I'm really close here, but started this process this summer...can't I find someone to work with me to get this approved?

**Comment by christalib** [comment]
Hi! Super sorry about that, we are all volunteers and working on the side. Unfortunately I can't help you with that project, but please be patient. I'm sure eventually someone will :)

**Comment by michielbdejong** [comment]
Sorry, yes, what Chris said!

You could help by uploading a 72x72 pixel logo to https://github.com/tosdr/tosdr.org/upload/master/src/logo

**Comment by RambosRide** [comment]
> 
> 
> Hi! Super sorry about that, we are all volunteers and working on the side. Unfortunately I can't help you with that project, but please be patient. I'm sure eventually someone will :)

Thanks for responding! 

I'd like to be able to help more, I signed up to contribute. Seems like all I can do is annotate services but not do any approvals.

**Comment by RambosRide** [comment]
> 
> 
> Sorry, yes, what Chris said!
> 
> You could help by uploading a 72x72 pixel logo to https://github.com/tosdr/tosdr.org/upload/master/src/logo

Hello - I went to the link, I'm logged into Github..but this is the message I get...

> Uploads are disabled.
> File uploads require push access to this repository.

**Comment by michielbdejong** [comment]
Sorry, hadn't realised you wouldn't be allowed to upload. Did it now - https://tosdr.org/img/logo/420a3-com.png should appear online shortly

**Comment by JustinBack** [comment]
Closing this issue, as its stale
