### ISSUE TITLE
Questions about project and roadmap

### ISSUE THREAD

**Issue by erotavlas-turbo** [tosdr/tosdr.org#230]
Hi,
I found this great project.
1) Is still under development? The latest updated is of 2018.
2) Why do many Web sites have a classification, but it is not showed by the plug in?
3) Are you planning a translation project?
4) Do you have any roadmap?
Thank you

**Comment by Vinnl** [comment]
Hi @erotavlas-turbo,

# Is the project still active?

Yes, in the sense that people are actively reviewing websites. You can [see](https://github.com/tosdr/tosdr.org) that the latest commit was six days ago.

However, there certainly is a shortage of software developers who have time to work on the software side, so the website and contribution tool at edit.tosdr.org haven't seen any significant new developments in a while.

# Why do many Web sites have a classification, but it is not showed by the plug in?

I'm not quite sure what you mean here. As far as I know all the sites with a classification on tosdr.org are also shown in our browser extension? (Additionally, are you referring to our own browser extension? People also tend to confuse it with the DuckDuckGo browser extension, which we have no control over. I believe that one gives unrated websites a "B" classification.)

# Translations

We'd like translations, and I believe there is a French version somewhere (@michielbdejong might know more about that), but again, the lack of technical contributors is a challenge here.

# Roadmap

We don't really have any; it's mostly determined by who wants to work on something, and then actually does that.

Thanks for your interest. I'll close the issue now to keep our issue tracker clean, but feel free to re-open it if you have more questions. (Or send an email to `team` [at] our domain.)

**Comment by erotavlas-turbo** [comment]
Thank you for the useful answers. I could participate in the future as translator. About classification, I mean that Web site as [whatsapp](https://edit.tosdr.org/services/198), [instagram](https://edit.tosdr.org/services/219), etc. have a classification, but it is not showed by the extension or on the Web site https://tosdr.org/index.html#services.

**Comment by Vinnl** [comment]
Ah, so I think you mean that edit.tosdr.org shows a rating, but it's not published to the website or extension? That's because the reviews haven't been marked as [complete](https://github.com/tosdr/tosdr.org/wiki/checklist) yet, because not every item on that checklist has an approved point detailing it.

**Comment by erotavlas-turbo** [comment]
> Ah, so I think you mean that edit.tosdr.org shows a rating, but it's not published to the website or extension? That's because the reviews haven't been marked as [complete](https://github.com/tosdr/tosdr.org/wiki/checklist) yet, because not every item on that checklist has an approved point detailing it.

Well, as I imagined. Can I help with this?

**Comment by Vinnl** [comment]
Certainly! You could add new Points for items on the checklist that are not currently covered to make it more complete. A Curator can then approve those Points and mark the review as complete - but keep in mind that our Curators are volunteers with limited time as well.

If you'd like to be a Curator, I think that might be possible as well - but @michielbdejong knows more about that.

**Comment by erotavlas-turbo** [comment]
@Vinnl of course, I can contribute in my free time. I think that the project is great.
